##Estudiante: Conde Ajururo Cristhian
Trabajo Final
Resuelva los siguientes ejercicios

1) Dado el siguiente archivo Precio_viviendas_Australia.csv, realice la regresión lineal múltiple para predecir el precio de viviendas ubicadas en Melbourne Australia.

In [56]:
import numpy as np
import pandas as pd

In [57]:
data = pd.read_csv('/content/drive/MyDrive/Precio_viviendas_Australia.csv')
data

         Suburbio           Direccion Habitaciones  ...    CPI Ultimo_CPI Distancia2
0       Footscray    202/51 Gordon St            1  ...  108.6      108.2        8.1
1       Caulfield          30 Pyne St            4  ...  109.4      108.6       12.8
2          Coburg     171 Moreland Rd            4  ...  108.2      108.4        6.8
3          Albion       8/6 Ridley St            1  ...  108.2      108.4       14.4
4          Albion  10/117 Anderson Rd            1  ...  108.6      108.2       14.1
...           ...                 ...          ...  ...    ...        ...        ...
9378     Armadale    367 Dandenong Rd            6  ...  108.6      108.2        9.7
9379  South Yarra         18 Avoca St            4  ...  108.6      108.2        4.9
9380          Kew          7 Wimba Av            5  ...  108.6      108.2        9.4
9381       Toorak        17 Albany Rd            3  ...  108.6      108.2        8.8
9382          Kew         15 Barry St            6  ...  108.6      108.2        7.6

[9383 rows x 13 columns]

In [58]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9383 entries, 0 to 9382
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Suburbio      9383 non-null   object
 1   Direccion     9383 non-null   object
 2   Habitaciones  9383 non-null   object
 3   Tipo          9383 non-null   object
 4   Precio        9383 non-null   object
 5   Metodo        9383 non-null   object
 6   VendedorG     9383 non-null   object
 7   Fecha         9383 non-null   object
 8   Distancia     9383 non-null   object
 9   Semana        9383 non-null   object
 10  CPI           9383 non-null   object
 11  Ultimo_CPI    9383 non-null   object
 12  Distancia2    9383 non-null   object
dtypes: object(13)
memory usage: 953.1+ KB

In [60]:
data.describe()

         Suburbio       Direccion Habitaciones  ...    CPI Ultimo_CPI Distancia2
count        9383            9383         9383  ...   9383       9383       9383
unique        143            8907           11  ...      5          5        276
top     Reservoir  2/54 Pender St            3  ...  108.6      108.2       14.4
freq          359               4         3712  ...   4339       4339        100

[4 rows x 13 columns]

In [61]:
#cambiamos la columna 'habitaciones' a tipo numerico
data['Habitaciones'] = pd.to_numeric(data['Habitaciones'], errors = 'coerce') 
data

         Suburbio           Direccion  ...  Ultimo_CPI Distancia2
0       Footscray    202/51 Gordon St  ...       108.2        8.1
1       Caulfield          30 Pyne St  ...       108.6       12.8
2          Coburg     171 Moreland Rd  ...       108.4        6.8
3          Albion       8/6 Ridley St  ...       108.4       14.4
4          Albion  10/117 Anderson Rd  ...       108.2       14.1
...           ...                 ...  ...         ...        ...
9378     Armadale    367 Dandenong Rd  ...       108.2        9.7
9379  South Yarra         18 Avoca St  ...       108.2        4.9
9380          Kew          7 Wimba Av  ...       108.2        9.4
9381       Toorak        17 Albany Rd  ...       108.2        8.8
9382          Kew         15 Barry St  ...       108.2        7.6

[9383 rows x 13 columns]

In [62]:
#hacemos lo mismo con las siguientes columnas
data['Precio'] = pd.to_numeric(data['Precio'], errors = 'coerce') 
data['Distancia'] = pd.to_numeric(data['Distancia'], errors = 'coerce') 
data['Semana'] = pd.to_numeric(data['Semana'], errors = 'coerce') 
data['CPI'] = pd.to_numeric(data['CPI'], errors = 'coerce')
data['Ultimo_CPI'] = pd.to_numeric(data['Ultimo_CPI'], errors = 'coerce') 
data['Distancia2'] = pd.to_numeric(data['Distancia2'], errors = 'coerce')

In [63]:
data.info()
data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9383 entries, 0 to 9382
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Suburbio      9383 non-null   object
 1   Direccion     9383 non-null   object
 2   Habitaciones  9382 non-null   float64
 3   Tipo          9383 non-null   object
 4   Precio        9382 non-null   float64
 5   Metodo        9383 non-null   object
 6   VendedorG     9383 non-null   object
 7   Fecha         9383 non-null   object
 8   Distancia     9382 non-null   float64
 9   Semana        9382 non-null   float64
 10  CPI           9382 non-null   float64
 11  Ultimo_CPI    9382 non-null   float64
 12  Distancia2    9382 non-null   float64
dtypes: float64(7), object(6)
memory usage: 953.1+ KB

Suburbio        0
Direccion       0
Habitaciones    1
Tipo            0
Precio          1
Metodo          0
VendedorG       0
Fecha           0
Distancia       1
Semana          1
CPI             1
Ultimo_CPI      1
Distancia2      1
dtype: int64

In [64]:
#reemplazamos los valores nulos con 0 y convertimos a valor entero las siguientes colunmas
data.fillna(0, inplace = True)
data['Semana'] = data['Semana'].astype('int')
data['Precio'] = data['Precio'].astype('int')
data['Habitaciones'] = data['Habitaciones'].astype('int')
data

         Suburbio           Direccion  ...  Ultimo_CPI Distancia2
0       Footscray    202/51 Gordon St  ...       108.2        8.1
1       Caulfield          30 Pyne St  ...       108.6       12.8
2          Coburg     171 Moreland Rd  ...       108.4        6.8
3          Albion       8/6 Ridley St  ...       108.4       14.4
4          Albion  10/117 Anderson Rd  ...       108.2       14.1
...           ...                 ...  ...         ...        ...
9378     Armadale    367 Dandenong Rd  ...       108.2        9.7
9379  South Yarra         18 Avoca St  ...       108.2        4.9
9380          Kew          7 Wimba Av  ...       108.2        9.4
9381       Toorak        17 Albany Rd  ...       108.2        8.8
9382          Kew         15 Barry St  ...       108.2        7.6

[9383 rows x 13 columns]

In [66]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9383 entries, 0 to 9382
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Suburbio      9383 non-null   object
 1   Direccion     9383 non-null   object
 2   Habitaciones  9383 non-null   int64
 3   Tipo          9383 non-null   object
 4   Precio        9383 non-null   int64
 5   Metodo        9383 non-null   object
 6   VendedorG     9383 non-null   object
 7   Fecha         9383 non-null   object
 8   Distancia     9383 non-null   float64
 9   Semana        9383 non-null   int64
 10  CPI           9383 non-null   float64
 11  Ultimo_CPI    9383 non-null   float64
 12  Distancia2    9383 non-null   float64
dtypes: float64(4), int64(3), object(6)
memory usage: 953.1+ KB

In [67]:
#Extraemos del dataset los datos que nos serviran para ingresarlos en el metodo de regresion lineal
X = data.drop(['Suburbio', 'Direccion','Tipo','Metodo', 'VendedorG','Fecha','Precio'], axis=1)
X

      Habitaciones  Distancia  Semana    CPI  Ultimo_CPI  Distancia2
0                1        6.4      32  108.6       108.2         8.1
1                4        8.9      57  109.4       108.6        12.8
2                4        7.8      19  108.2       108.4         6.8
3                1       13.9      18  108.2       108.4        14.4
4                1       13.9      30  108.6       108.2        14.1
...            ...        ...     ...    ...         ...         ...
9378             6        6.3      34  108.6       108.2         9.7
9379             4        3.3      42  108.6       108.2         4.9
9380             5        5.6      32  108.6       108.2         9.4
9381             3        4.6      38  108.6       108.2         8.8
9382             6        5.6      29  108.6       108.2         7.6

[9383 rows x 6 columns]

In [68]:
#El get_dummiesmétodo de la biblioteca de pandas convierte columnas categóricas
#en columnas numéricas. Luego, .iloc[:,1:]ignora la primera columna y devuelve 
#el resto de las columnas,esto se debe a que 
#siempre podemos representar "n" categorías con "n - 1" columnas.
#en este caso convertiremos las columnas "metodo" y "tipo"
metodo = pd.get_dummies(data.Metodo).iloc[:,1:]
metodo

      PI  S  SA  SP  VB
0      1  0   0   0   0
1      1  0   0   0   0
2      1  0   0   0   0
3      1  0   0   0   0
4      0  1   0   0   0
...   .. ..  ..  ..  ..
9378   0  1   0   0   0
9379   0  1   0   0   0
9380   0  1   0   0   0
9381   0  1   0   0   0
9382   0  1   0   0   0

[9383 rows x 5 columns]

In [69]:
tipo = pd.get_dummies(data.Tipo).iloc[:,1:]
tipo

      h  t  u
0     0  0  1
1     1  0  0
2     1  0  0
3     0  0  1
4     0  0  1
...  .. .. ..
9378  1  0  0
9379  1  0  0
9380  1  0  0
9381  1  0  0
9382  1  0  0

[9383 rows x 3 columns]

In [70]:
#concatenamos las nuevas columnas a nuestro X 
X = pd.concat([tipo,X,metodo], axis=1)
X

      h  t  u  Habitaciones  Distancia  Semana  ...  Distancia2  PI  S  SA  SP  VB
0     0  0  1             1        6.4      32  ...         8.1   1  0   0   0   0
1     1  0  0             4        8.9      57  ...        12.8   1  0   0   0   0
2     1  0  0             4        7.8      19  ...         6.8   1  0   0   0   0
3     0  0  1             1       13.9      18  ...        14.4   1  0   0   0   0
4     0  0  1             1       13.9      30  ...        14.1   0  1   0   0   0
...  .. .. ..           ...        ...     ...  ...         ...  .. ..  ..  ..  ..
9378  1  0  0             6        6.3      34  ...         9.7   0  1   0   0   0
9379  1  0  0             4        3.3      42  ...         4.9   0  1   0   0   0
9380  1  0  0             5        5.6      32  ...         9.4   0  1   0   0   0
9381  1  0  0             3        4.6      38  ...         8.8   0  1   0   0   0
9382  1  0  0             6        5.6      29  ...         7.6   0  1   0   0   0

[9383 rows x 14 columns]

In [71]:
#Extramos del dataset la columna objetivo, esta sera nuestra y 
y= data.get(['Precio'])
y

       Precio
0       85000
1      131000
2      145000
3      145000
4      185000
...       ...
9378  5525000
9379  5700000
9380  6240000
9381  6250000
9382  6500000

[9383 rows x 1 columns]

In [72]:
#implementando la regresión
from sklearn.model_selection import train_test_split
from sklearn import linear_model
#Separando los datos de train en entrenamiento y prueba
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

In [73]:
x_train

      h  t  u  Habitaciones  Distancia  Semana  ...  Distancia2  PI  S  SA  SP  VB
5928  0  0  1             3        4.6      17  ...         6.5   0  1   0   0   0
2388  0  0  1             2       11.7      41  ...        16.8   0  1   0   0   0
8047  1  0  0             3        2.8      57  ...         0.9   0  1   0   0   0
2512  0  0  1             1        1.5      17  ...         1.9   0  0   0   1   0
5852  1  0  0             3        7.8      28  ...         8.8   0  0   0   1   0
...  .. .. ..           ...        ...     ...  ...         ...  .. ..  ..  ..  ..
3482  0  1  0             2       12.1      13  ...        19.9   0  1   0   0   0
4203  1  0  0             3       13.5      30  ...        15.6   0  1   0   0   0
5109  1  0  0             3        2.6      35  ...         3.3   0  1   0   0   0
1011  0  1  0             2       11.1      58  ...        14.6   0  1   0   0   0
94    0  0  1             1        5.9      57  ...         5.0   0  1   0   0   0

[7506 rows x 14 columns]

In [74]:
#definimos el algoritmo a utilizar
lr_multiple=linear_model.LinearRegression()

#entrenando al modelo
lr_multiple.fit(x_train,y_train)

LinearRegression()

In [75]:
#Realizola predicción
y_pred_multiple=lr_multiple.predict(x_test)

In [76]:
#Datos del modelo
print('valor de la pendiente o coeficiente')
print(lr_multiple.coef_)

valor de la pendiente o coeficiente
[[ 4.93856405e+04 -1.73238875e+05 -2.87078451e+05  3.52699975e+05
  -4.98623632e+04  9.36094641e+02  8.52264296e+04 -7.97884284e+04
   2.89158317e+02 -1.27441478e+05 -6.32047617e+04  2.49822828e+04
  -1.94206968e+05 -5.10607616e+04]]

In [77]:
#Valor de la intersección
print('Valor de la intersección')
print(lr_multiple.intercept_)

Valor de la intersección
[-1.20373443e-07]

In [78]:
print('Precisión del modelo')
print(lr_multiple.score(x_train,y_train))

Precisión del modelo
0.44763204723139616

In [79]:
#Calculando RMSE
import math
from sklearn import  metrics
MSE=metrics.mean_squared_error(y_test,y_pred_multiple)
print('RMSE=%.02f'%math.sqrt(MSE))

RMSE=489738.42

In [80]:
#Dado que no se consideraron algunas columnas para el analisis,
#el resultado del modelo de regresion lineal no es muy preciso